services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: P@ssword
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - nestjs

  

volumes:
  postgres-data:

networks:
  nestjs:
    name: nestjs-network