services:

  postgres:
    image: postgres:alpine
    restart: always
    container_name: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: P@ssword
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - nestjs

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/root/redis"
      - "redis-config:/usr/local/etc/redis/redis.conf"
    # environment:
    #   - REDIS_PASSWORD=my-password
    #   - REDIS_PORT=6379
    #   - REDIS_DATABASES=16
    networks:
      - nestjs

  

volumes:
  postgres-data:
  redis-data:
  redis-config:

networks:
  nestjs:
    name: nestjs-network